### PR TITLE
Update README.md -- add installation instructions

### PR DESCRIPTION
**Pull request by randolf**
Add installation instructions and an example of how to use this extension.

### CODE REVIEW

**Comment by okbob** [comment]
merged, thank you for PR

**Comment by randolf** [comment]
You're welcome.  This is a really neat project; thanks for putting the work into it.

**Comment by okbob** [comment]
pá 2. 2. 2024 v 5:58 odesílatel Randolf Richardson 張文道 <
***@***.***> napsal:

> You're welcome. This is a really neat project; thanks for putting the work
> into it.
>

I needed it for a diagnostic for one customer, and it is a small utility.
Now I thinking enhance it about sum of memory contexts  - it can be faster
than usage SQL, and it can be available for some older databases without
possibility to see memory contexts in SQL.

**Comment by randolf** [comment]
> I needed it for a diagnostic for one customer, and it is a small utility. Now I thinking enhance it about sum of memory contexts - it can be faster than usage SQL, and it can be available for some older databases without possibility to see memory contexts in SQL. —

That's a great idea, and also useful for showing end-users an overview of memory usage.

**Pull request merged**
